update build script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,26 +3,30 @@
 
 function print_help
 { 
-    # echo "" ;
-    echo -e "\x1B[32mConfigure options:\033[0m" >&2 ;
     echo "" ;
+    echo -e "\x1B[32mTraME Configure options:\033[0m" >&2 ;
     echo "-c    Coverage build" ;
-    echo "-d    Development build (install paths set to current directory)" ;
+    echo "-d    Development build" ;
     echo "-g    Debugging build (optimization flags set to -O0 -g)" ;
     echo "-h    Print help" ;
+    echo "-i    Install path (default: current directory)" ;
+    echo "        Example: /usr/local" ;
     echo "-l    Enable wrappers for a linear programming library" ;
     echo "        Examples: -l glpk or -l gurobi" ;
     echo "-m    Specify the BLAS and Lapack libraries to link against" ; 
     echo "        Examples: -m \"-lopenblas\" or -m \"-framework Accelerate\"" ;
     echo "-o    Compiler optimization options; defaults to -O3 -march=native" ;
     echo "-p    Enable OpenMP parallelization features" ;
+    echo "" ;
 }
 
-while getopts hcdl:m:o:pv option; do
+while getopts hcdgl:m:o:pv option; do
     case "${option}" in
         h) print_help; exit 2;;
         c) TRAME_COVERAGE_BUILD="y";;
         d) TRAME_BUILD="dev";;
+        g) TRAME_DEBUG_BUILD="y";;
+        i) TRAME_INSTALL_PATH=${OPTARG};;
         l) TRAME_LP=${OPTARG};;
         m) TRAME_MATRIX_OPS=${OPTARG};;
         o) TRAME_OPT=${OPTARG};;
@@ -42,6 +46,10 @@ if [ -z ${FC+x} ]; then
     FC=gfortran
 fi
 
+echo ""
+echo -e "\x1B[32mTraME Configuration...\033[0m" >&2 ;
+echo ""
+
 # compiler checks
 
 IS_DARWIN=$($CXX -dumpmachine 2>&1 | grep -i -c "darwin")
@@ -49,20 +57,8 @@ GCC_COMPILER=$($CXX --version 2>&1 | grep -i -c -E "gcc")
 GFC_COMPILER=$($FC --version 2>&1 | grep -i -c -E "gcc")
 # APPLE_COMPILER=$($CXX --version 2>&1 | grep -i -c -E 'apple llvm')
 
-# announcements
-
-echo ""
-if [[ "${TRAME_BUILD}" == "dev" ]]; then
-    echo "TraME: dev version"
-fi
-
-if [[ "${TRAME_COVERAGE_BUILD}" == "y" ]]; then 
-    echo "TraME: coverage build"
-fi
-
 # get working directory
 WDIR=${PWD}
-
 
 # look for Armadillo
 if [ -z ${ARMA_INCLUDE_PATH+x} ]; then
@@ -79,7 +75,7 @@ if [ -z ${ARMA_INCLUDE_PATH+x} ]; then
 
     if [[ $ARMA_INCLUDE_PATH == "" ]]; then
         echo ""
-        echo "TraME: cannot find armadillo files. Cloning from GitHub"
+        echo -e "\x1B[31m  - note: cannot find Armadillo files. Cloning from GitHub\033[0m" >&2 ;
         echo ""
 
         mkdir ${WDIR}/arma_tmp
@@ -92,15 +88,14 @@ if [ -z ${ARMA_INCLUDE_PATH+x} ]; then
     fi
 fi
 
-echo "TraME: ARMA_INCLUDE_PATH set to ${ARMA_INCLUDE_PATH}"
-
 # set build and optimization flags
 
 if [[ "${TRAME_COVERAGE_BUILD}" == "y" ]]; then 
     TRAME_OPT_FLAGS="-O0 -g --coverage -fno-inline -fno-inline-small-functions -fno-default-inline"
+elif [[ "${TRAME_DEBUG_BUILD}" == "y" ]]; then 
+    TRAME_OPT_FLAGS="-O0 -g"
 else
     if [[ "${TRAME_OPT}" == "" ]]; then
-        # TRAME_OPT_FLAGS="-Ofast -march=native -DARMA_NO_DEBUG"
         # echo "TraME: experimental optimization enabled; use of NaN or +/-Inf not recognized"
         TRAME_OPT_FLAGS="-O3 -march=native -flto -DARMA_NO_DEBUG"
     else
@@ -108,11 +103,8 @@ else
     fi
 
     if [[ "${TRAME_PARALLEL}" == "y" ]]; then
-        echo "TraME: using OpenMP"
         TRAME_OPT_FLAGS="${TRAME_OPT_FLAGS} -fopenmp -DTRAME_USE_OPENMP -DARMA_USE_OPENMP -DARMA_USE_CXX11"
     fi
-
-    echo "TraME: optimization flags set to: ${TRAME_OPT_FLAGS}"
 fi
 
 TRAME_WARN_FLAGS="-Wall"
@@ -121,12 +113,11 @@ TRAME_WARN_FLAGS="-Wall"
 
 TRAME_SHLIB_NAME="libtrame.so"
 
-if [[ !("${TRAME_BUILD}" == "dev") ]]; then
-    if [ -z ${TRAME_INSTALL_PATH+x} ]; then
-        TRAME_INSTALL_PATH="/usr/local"
-    fi
-    echo ""
-    echo "TraME: install path set to ${TRAME_INSTALL_PATH}"
+if [[ "${TRAME_INSTALL_PATH}" == "" ]]; then
+    TRAME_INSTALL_PATH="${WDIR}"
+    TRAME_INSTALL_LIB_PATH="${WDIR}"
+else
+    TRAME_INSTALL_LIB_PATH="${TRAME_INSTALL_PATH}/lib"
 fi
 
 #
@@ -138,11 +129,7 @@ if [[ $OSTYPE == darwin* ]] ; then
 
         TRAME_BLAS_LAPACK="${TRAME_LAPACK_LIBS} ${TRAME_BLAS_LIBS}"
     else
-        if [[ "${TRAME_BUILD}" == "dev" ]]; then
-            TRAME_SHLIB_FLAGS="-dynamiclib -install_name "${WDIR}/${TRAME_SHLIB_NAME}" -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress"
-        else
-            TRAME_SHLIB_FLAGS="-dynamiclib -install_name "${TRAME_INSTALL_PATH}/lib/${TRAME_SHLIB_NAME}" -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress"
-        fi
+        TRAME_SHLIB_FLAGS="-dynamiclib -install_name "${TRAME_INSTALL_LIB_PATH}/${TRAME_SHLIB_NAME}" -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress"
 
         TRAME_BLAS_LAPACK="-framework Accelerate"
     fi
@@ -162,14 +149,13 @@ if [[ $OSTYPE == darwin* ]] ; then
         grb_lib_latest=${grb_lib_path[0]}
         grb_lib_name=$(basename ${grb_lib_latest})
         grb_lib_num=${grb_lib_name//[^0-9]/}
-
+        
+        TRAME_LP="Gurobi"
         LP_INCLUDE_PATH="-DTRAME_USE_GUROBI -I$grb_latest/mac64/include"
         LP_LIB_PATH="-L$grb_latest/mac64/lib"
-        LP_LIBS="-lgurobi${grb_lib_num}"
+        LP_LIB_FLAGS="-lgurobi${grb_lib_num}"
         LP_LIB_RPATH="-Wl,-rpath,$grb_latest/mac64/lib"
 
-        echo ""
-        echo "TraME: using Gurobi. LP_INCLUDE_PATH set to ${LP_INCLUDE_PATH}"
     else
         # look for GLPK, or download it
         if [ -f ${WDIR}/glpk_tmp/include/glpk.h ]; then
@@ -189,7 +175,7 @@ if [[ $OSTYPE == darwin* ]] ; then
             LP_LIB_PATH="-L/opt/local/lib"
         else
             echo ""
-            echo "TraME: cannot find a linear programming solver. Downloading and building GLPK."
+            echo -e "\x1B[31m  - note: cannot find a linear programming solver. Downloading and building GLPK.\033[0m" >&2 ;
             echo ""
 
             mkdir ${WDIR}/glpk_tmp
@@ -220,20 +206,14 @@ if [[ $OSTYPE == darwin* ]] ; then
             LP_INCLUDE_PATH="-DTRAME_USE_GLPK -I${WDIR}/glpk_tmp/include"
             LP_LIB_PATH="-L${WDIR}/glpk_tmp/lib"
         fi
-    
-    LP_LIBS="-lglpk"
+    TRAME_LP="GLPK"
+    LP_LIB_FLAGS="-lglpk"
     LP_LIB_RPATH=
 
-    echo ""
-    echo "TraME: using GLPK. LP_INCLUDE_PATH set to ${LP_INCLUDE_PATH}"
     fi
 elif [[ $OSTYPE == *linux* ]] ; then
     TRAME_OPT_FLAGS="-fPIC ${TRAME_OPT_FLAGS}"
-    if [[ "${TRAME_BUILD}" == "dev" ]]; then
-        TRAME_SHLIB_FLAGS="-fPIC -shared -L${WDIR} -Wl,-Bsymbolic-functions -Wl,-z,relro "
-    else
-        TRAME_SHLIB_FLAGS="-fPIC -shared -L/usr/lib -Wl,-Bsymbolic-functions -Wl,-z,relro "
-    fi
+    TRAME_SHLIB_FLAGS="-fPIC -shared -L${TRAME_INSTALL_LIB_PATH} -Wl,-Bsymbolic-functions -Wl,-z,relro "
     TRAME_BLAS_LAPACK="-lblas -llapack"
 
     # look for any Gurobi directories, then choose the latest one
@@ -251,13 +231,12 @@ elif [[ $OSTYPE == *linux* ]] ; then
         grb_lib_name=$(basename ${grb_lib_latest})
         grb_lib_num=${grb_lib_name//[^0-9]/}
 
+        TRAME_LP="Gurobi"
         LP_INCLUDE_PATH="-DTRAME_USE_GUROBI -I$grb_latest/linux64/include"
         LP_LIB_PATH="-L$grb_latest/linux64/lib"
-        LP_LIBS="-lgurobi${grb_lib_num}"
+        LP_LIB_FLAGS="-lgurobi${grb_lib_num}"
         LP_LIB_RPATH="-Wl,-rpath,$grb_latest/linux64/lib"
 
-        echo ""
-        echo "TraME: using Gurobi. LP_INCLUDE_PATH set to ${LP_INCLUDE_PATH}"
     else
         # look for GLPK, or download it
         if [ -f ${WDIR}/glpk_tmp/include/glpk.h ]; then
@@ -277,7 +256,7 @@ elif [[ $OSTYPE == *linux* ]] ; then
             LP_LIB_PATH="-L/opt/local/lib"
         else
             echo ""
-            echo "TraME: cannot find a linear programming solver. Downloading and building GLPK."
+            echo -e "\x1B[31m  - note: cannot find a linear programming solver. Downloading and building GLPK.\033[0m" >&2 ;
             echo ""
 
             mkdir ${WDIR}/glpk_tmp
@@ -309,22 +288,16 @@ elif [[ $OSTYPE == *linux* ]] ; then
             LP_LIB_PATH="-L${WDIR}/glpk_tmp/lib"
         fi
     
-    LP_LIBS="-lglpk"
+    TRAME_LP="GLPK"
+    LP_LIB_FLAGS="-lglpk"
     LP_LIB_RPATH=
 
-    echo ""
-    echo "TraME: using GLPK. LP_INCLUDE_PATH set to ${LP_INCLUDE_PATH}"
     fi
 elif [[ $OSTYPE == *cygwin* ]] ; then
     TRAME_SHLIB_NAME="libtrame.dll"
     TRAME_OPT_FLAGS="${TRAME_OPT_FLAGS} -DARMA_DONT_PRINT_CXX11_WARNING"
 
-    if [[ "${TRAME_BUILD}" == "dev" ]]; then
-        # TRAME_SHLIB_FLAGS="-shared -L${WDIR} -Wl,-Bsymbolic-functions -Wl,-z,relro "
-        TRAME_SHLIB_FLAGS="-shared -L${WDIR} "
-    else
-        TRAME_SHLIB_FLAGS="-shared -L/usr/local/lib "
-    fi
+    TRAME_SHLIB_FLAGS="-shared -L${TRAME_INSTALL_LIB_PATH} "
     TRAME_BLAS_LAPACK="-lblas -llapack"
 
     # look for any Gurobi directories, then choose the latest one
@@ -341,14 +314,13 @@ elif [[ $OSTYPE == *cygwin* ]] ; then
         grb_lib_latest=${grb_lib_path[0]}
         grb_lib_name=$(basename ${grb_lib_latest})
         grb_lib_num=${grb_lib_name//[^0-9]/}
-
+        
+        TRAME_LP="Gurobi"
         LP_INCLUDE_PATH="-DTRAME_USE_GUROBI -I$grb_latest/win64/include"
         LP_LIB_PATH="-L$grb_latest/win64/bin"
-        LP_LIBS="-lgurobi${grb_lib_num}"
+        LP_LIB_FLAGS="-lgurobi${grb_lib_num}"
         LP_LIB_RPATH="-Wl,-rpath,$grb_latest/win64/bin"
 
-        echo ""
-        echo "TraME: using Gurobi. LP_INCLUDE_PATH set to ${LP_INCLUDE_PATH}"
     else
         # look for GLPK, or download it
         if [ -f ${WDIR}/glpk_tmp/include/glpk.h ]; then
@@ -368,7 +340,7 @@ elif [[ $OSTYPE == *cygwin* ]] ; then
             LP_LIB_PATH="-L/opt/local/lib"
         else
             echo ""
-            echo "TraME: cannot find a linear programming solver. Downloading and building GLPK."
+            echo -e "\x1B[31m  - note: cannot find a linear programming solver. Downloading and building GLPK.\033[0m" >&2 ;
             echo ""
 
             mkdir ${WDIR}/glpk_tmp
@@ -398,22 +370,22 @@ elif [[ $OSTYPE == *cygwin* ]] ; then
 
             LP_INCLUDE_PATH="-DTRAME_USE_GLPK -I${WDIR}/glpk_tmp/include"
             LP_LIB_PATH="-L${WDIR}/glpk_tmp/lib"
-            LP_LIBS="-lglpk"
+            LP_LIB_FLAGS="-lglpk"
             LP_LIB_RPATH=
         fi
     
-    LP_LIBS="-lglpk"
+    TRAME_LP="GLPK"
+    LP_LIB_FLAGS="-lglpk"
     LP_LIB_RPATH=
 
-    echo ""
-    echo "TraME: using GLPK. LP_INCLUDE_PATH set to ${LP_INCLUDE_PATH}"
     fi
 else
     TRAME_BLAS_LAPACK="-lblas -llapack"
 
+    TRAME_LP=""
     LP_INCLUDE_PATH=
     LP_LIB_PATH=
-    LP_LIBS=
+    LP_LIB_FLAGS=
     LP_LIB_RPATH=
 fi
 
@@ -421,8 +393,6 @@ fi
 
 if [[ !(-z ${TRAME_MATRIX_OPS+x}) ]]; then
     TRAME_BLAS_LAPACK="${TRAME_MATRIX_OPS}"
-    echo ""
-    echo "TraME: BLAS and Lapack libraries set to ${TRAME_BLAS_LAPACK}"
 fi
 
 if [[ "${TRAME_COVERAGE_BUILD}" == "y" ]]; then 
@@ -432,19 +402,78 @@ else
 fi
 
 if [ "$IS_DARWIN" -eq "1" ] && [ "$GCC_COMPILER" -eq "1" ]; then
-    echo ""
-    echo "TraME: To enable AVX features, your compiler will use the Apple LLVM assembler"
     TRAME_OPT_FLAGS="-Wa,-q ${TRAME_OPT_FLAGS}"
 fi
 
 TRAME_FC_OPT_FLAGS=$TRAME_OPT_FLAGS
 
 if [ "$IS_DARWIN" -eq "1" ] && [ "$GCC_COMPILER" -eq "0" ] && [ "$GFC_COMPILER" -eq "1" ]; then
-    echo ""
-    echo "TraME: To enable AVX features, your Fortran compiler will use the Apple LLVM assembler"
     TRAME_FC_OPT_FLAGS="-Wa,-q ${TRAME_FC_OPT_FLAGS}"
 fi
 
+#
+# final print:
+
+echo "  - OS: ${OSTYPE}"
+
+if [[ "${TRAME_BUILD}" == "dev" ]]; then
+    echo "  - Build version: development"
+elif [[ "${TRAME_COVERAGE_BUILD}" == "y" ]]; then
+    echo "  - Build version: coverage"
+elif [[ "${TRAME_DEBUG_BUILD}" == "y" ]]; then
+    echo "  - Build version: debug"
+else
+    echo "  - Build version: release"
+fi
+
+echo ""
+
+echo "  - ARMA_INCLUDE_PATH set to:"
+echo "    ${ARMA_INCLUDE_PATH}"
+echo "  - BLAS and Lapack libraries set to:"
+echo "    ${TRAME_BLAS_LAPACK}"
+
+echo ""
+
+echo "  - LP solver: ${TRAME_LP}"
+echo "    * LP_INCLUDE_PATH:"
+echo "      ${LP_INCLUDE_PATH}"
+echo "    * LP_LIB_PATH:"
+echo "      ${LP_LIB_PATH}"
+echo "    * LP_LIB_FLAGS:"
+echo "      ${LP_LIB_FLAGS}"
+
+echo ""
+
+if [[ "${TRAME_PARALLEL}" == "y" ]]; then
+    echo -e "  - OpenMP features: \x1B[32menabled\033[0m" >&2 ;
+else
+    echo -e "  - OpenMP features: \x1B[31mdisabled\033[0m" >&2 ;
+fi
+
+echo "  - optimization flags:"
+echo "    ${TRAME_OPT_FLAGS}"
+
+echo ""
+
+echo "  - TraME install path:"
+echo "    ${TRAME_INSTALL_PATH}"
+
+echo ""
+echo "  - Additional notes:"
+
+if [ "$IS_DARWIN" -eq "1" ] && [ "$GCC_COMPILER" -eq "1" ]; then
+    echo "    - To enable AVX features, your compiler will use the Apple LLVM"
+    echo "      assembler"
+fi
+
+if [ "$IS_DARWIN" -eq "1" ] && [ "$GCC_COMPILER" -eq "0" ] && [ "$GFC_COMPILER" -eq "1" ]; then
+    echo "    - To enable AVX features, your Fortran compiler will use the"
+    echo "      Apple LLVM assembler."
+fi
+
+echo ""
+echo -e "\x1B[32mConfiguration completed. Creating Makefile.\033[0m" >&2 ;
 echo ""
 
 # create Makefile
@@ -463,6 +492,6 @@ sed -e "s|@CC@|${CC}|" \
     -e "s|@TRAME_INSTALL_PATH@|${TRAME_INSTALL_PATH}|" \
     -e "s|@LP_INCLUDE_PATH@|${LP_INCLUDE_PATH}|" \
     -e "s|@LP_LIB_PATH@|${LP_LIB_PATH}|" \
-    -e "s|@LP_LIBS@|${LP_LIBS}|" \
+    -e "s|@LP_LIB_FLAGS@|${LP_LIB_FLAGS}|" \
     -e "s|@LP_LIB_RPATH@|${LP_LIB_RPATH}|" \
     Makefile.in > Makefile
